// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzcnvfqbbzkqyvolokvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Y252ZnFiYnprcXl2b2xva3Z0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MTA4MzUsImV4cCI6MjA4NzE4NjgzNX0.ONAGYoMOkaR0uKI0pHpjKrjhdT7vmJyOEdmpP58pQZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});